## Start of run_analysis.R ##
## -------------------------------------------------------
## One of the most exciting areas in all of data science right now is wearable 
## computing. Companies like Fitbit, Nike, and Jawbone Up are racing to develop 
## the most advanced algorithms to attract new users.
##
## Experiments have been carried out with a group of 30 volunteers within an age 
## bracket of 19-48 years. Each person performed six activities (WALKING, 
## WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a 
## smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer 
## and gyroscope, we captured 3-axial linear acceleration and 3-axial angular 
## velocity at a constant rate of 50Hz. The experiments have been video-recorded 
## to label the data manually. The obtained dataset has been randomly partitioned 
## into two sets, where 70% of the volunteers was selected for generating the 
## training data and 30% the test data. 
##
## This project attempts to merge these data into a tidy and readable format.
##

# Environment Setup
cat("[getdata-006.A2] Setting Up Environment","\n")
if (!require("data.table")) install.packages("data.table")
if (!require("reshape2")) install.packages("reshape2")
require("data.table") ; require("reshape2")

dataDir <- "./getdata-006/UCI HAR Dataset/"

# Preparing MetaData
cat("[getdata-006.A2] Preparing MetaData","\n")

activities <- read.table(paste(dataDir,"activity_labels.txt",sep=""))[,2]
features <- read.table(paste(dataDir,"features.txt",sep=""))[,2]

features.std <- grepl("-std()",features,fixed=TRUE)
features.mean <- grepl("-mean()",features,fixed=TRUE)

## The below function read and combine data from files generated by the 
## accelerometer and gyroscope. It accepts a 'set' input to determine the
## type of data to read, and returns the combined data as its output.

getDataSet <- function(set) {

# Assign file names
  cat("[getdata-006.A2]","\t","Getting '",set,"' Data","\n")
  featureFile <- paste(dataDir,set,"/X_",set,".txt",sep="")
  activityFile <- paste(dataDir,set,"/y_",set,".txt",sep="")
  subjectFile <- paste(dataDir,set,"/subject_",set,".txt",sep="")
  
# Read features
  cat("[getdata-006.A2]","\t\t\t","reading features","\n")
  featureData <- read.table(featureFile)
  names(featureData) <- features
  featureData = featureData[,(features.std|features.mean)]
  
# Read activities
  cat("[getdata-006.A2]","\t\t\t","reading activities","\n")
  activityData <- read.table(activityFile)
  activityData[,2] = activities[activityData[,1]]
  names(activityData) = c("ActivityID", "ActivityName")
  
# Read subjects
  cat("[getdata-006.A2]","\t\t\t","reading subjects","\n")
  subjectData <- read.table(subjectFile)
  names(subjectData) = "Subject"
  
# Return Binded Datasets
  cat("[getdata-006.A2]","\t","Combining Data","\n")
  return(cbind(as.data.table(subjectData),activityData,featureData))

}

## The below function gets the 'train' and 'test' datasets using the getDataSet 
## function above, merged and restructure the returned datasets, and applies
## average calculations before writting the tidied dataset to file.

runAnalysis <- function() {
  
# Get train & train dataset
  trainData <- getDataSet("train")
  testData <- getDataSet("test")

# Merge train & test dataset
  cat("[getdata-006.A2] Merging Datasets","\n")
  mergedData = rbind(trainData, testData)
  
# Assigning row and column labels
  rowID <- c("Subject", "ActivityID", "ActivityName")
  colID <- setdiff(colnames(mergedData), rowID)
  
# Apply mean function to dataset using dcast function
  cat("[getdata-006.A2] Melting Dataset","\n")
  meltData <- melt(mergedData,id=rowID,measure.vars=colID)
  
# Apply mean function to dataset using dcast function
  cat("[getdata-006.A2] Dcasting Dataset","\n")
  tidyData <- dcast(meltData,Subject+ActivityName~variable,mean)
  
# Apply mean function to dataset using dcast function
  cat("[getdata-006.A2] Writng Tidy Dataset to File","\n")
  write.table(tidyData,file=paste(dataDir,"tidydata.txt",sep=""))
  
}

# Running the analysis
  runAnalysis()

##
## Created By   : Eric Lim B G
## Created Date : 24-Aug-2014
## -------------------------------------------------------
## End of run_analysis.R ##
